"""Real-data figures 3, 4, 5, 7 from main-sweep judgments.
(1+2 regenerated by the inline script earlier; 6 waits on probe judgments.)

Usage: python -m sweep.make_real_figs
"""

import json
from collections import Counter, defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from .analyze import load, canon_identity, is_self

ROOT = Path(__file__).resolve().parent.parent
FIGS = ROOT / "post" / "figs"

CAT = ["#2a78d6", "#1baf7a", "#eda100", "#008300", "#4a3aa7", "#e34948", "#e87ba4", "#eb6834"]
SURFACE, INK, INK2, MUTED, GRID, BASE = "#fcfcfb", "#0b0b0b", "#52514e", "#898781", "#e1e0d9", "#c3c2b7"
plt.rcParams.update({
    "figure.facecolor": SURFACE, "axes.facecolor": SURFACE,
    "font.family": "DejaVu Sans", "text.color": INK,
    "axes.edgecolor": BASE, "axes.labelcolor": INK2,
    "xtick.color": MUTED, "ytick.color": MUTED, "font.size": 9,
})


def style(ax, bottom=True):
    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_visible(bottom)
    ax.tick_params(length=0)


def save(fig, name):
    FIGS.mkdir(parents=True, exist_ok=True)
    fig.savefig(FIGS / name, dpi=200, bbox_inches="tight", facecolor=SURFACE)
    plt.close(fig)
    print(f"  {name}")


_ADJ = None


def _adjudications():
    """{adj_key: verdict} from the adjudication pass, loaded once."""
    global _ADJ
    if _ADJ is None:
        _ADJ = {}
        p = ROOT / "results" / "adjudications.jsonl"
        if p.exists():
            for l in open(p, encoding="utf-8"):
                try:
                    r = json.loads(l)
                except json.JSONDecodeError:
                    continue
                if r.get("verdict"):
                    _ADJ[r["adj_key"]] = r["verdict"]
    return _ADJ


def foreign_claims(j):
    """Canonical foreign identities claimed, after every FP filter:
      * canon (generics/cross-script self-names handled in analyze.canon)
      * role_play reasoning traces dropped
      * adjudication: if a record was reviewed and NOT confirmed genuine_foreign,
        it returns empty (the robust FP removal). Records with no adjudication
        (e.g. before the pass runs) fall back to canon+role_play only.
    """
    jm = j["judgment"]
    fam = j.get("family", "")
    fields = ["claimed_name", "claimed_creator"]
    if jm.get("reasoning_identity_stance") != "role_play":
        fields += ["reasoning_claimed_name", "reasoning_claimed_creator"]
    out = set()
    for f in fields:
        c = canon_identity(jm.get(f))
        if c and not is_self(c, fam, j.get("aliases", []), j["expected_identity"]):
            out.add(c)
    if out:
        adj = _adjudications().get(f"{j['resume_key']}::t{j.get('turn_index', 0)}")
        if adj is not None and adj != "genuine_foreign":
            return set()
    return out


CREATOR_TO_BRAND = {"anthropic": "claude", "openai": "chatgpt", "google": "gemini",
                    "alibaba": "qwen", "meta": "llama", "moonshot": "kimi",
                    "nvidia": "nvidia", "baidu": "ernie", "tencent": "hunyuan",
                    "bytedance": "doubao", "microsoft": "microsoft"}


def fig3(rows, reg):
    per_family = defaultdict(Counter)
    for j in rows:
        if j["prompt_category"] in ("probe_cross", "system_probe"):
            continue
        # dedupe name+creator to one brand per record (see make_big_figs.gather)
        cols = {("hallucinated/other" if c.startswith("other:")
                 else CREATOR_TO_BRAND.get(c, c)) for c in foreign_claims(j)}
        for c in cols:
            per_family[j.get("family", "?")][c] += 1

    fams = sorted(per_family, key=lambda f: -sum(per_family[f].values()))[:10]
    all_claims = Counter()
    for f in fams:
        all_claims.update(per_family[f])
    top_claims = [c for c, _ in all_claims.most_common(7)]
    if "hallucinated/other" in top_claims:
        top_claims.remove("hallucinated/other")
    top_claims = top_claims[:6] + ["hallucinated/other"]

    fig, ax = plt.subplots(figsize=(8.8, 4.8))
    left = np.zeros(len(fams))
    for k, cl in enumerate(top_claims):
        vals = []
        for f in fams:
            tot = sum(per_family[f].values())
            v = per_family[f].get(cl, 0)
            if cl == "hallucinated/other":
                v = tot - sum(per_family[f].get(c, 0) for c in top_claims[:-1])
            vals.append(100 * v / tot if tot else 0)
        ax.barh([f for f in fams][::-1], np.array(vals)[::-1], left=left[::-1],
                height=0.62, color=CAT[k % 8], label=cl,
                edgecolor=SURFACE, linewidth=2, zorder=3)
        left += np.array(vals)
    ax.set_xlim(0, 100)
    ax.set_xlabel("share of that family's foreign identity claims (%)")
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.16), ncol=7, frameon=False, fontsize=8)
    style(ax)
    n_claims = sum(sum(c.values()) for c in per_family.values())
    ax.set_title(f"Who claims to be whom — {n_claims:,} foreign claims across {len(per_family)} claimant families (top 10 shown)",
                 loc="left", fontsize=11, pad=12)
    save(fig, "fig3_identity_flow.png")


def fig4(rows, reg):
    targets = ["chatgpt", "claude", "gemini", "deepseek", "qwen", "llama",
               "grok", "kimi", "mistral", "doubao"]
    yes = defaultdict(set)
    for j in rows:
        if j["prompt_category"] != "probe_cross":
            continue
        t = j["prompt_id"].replace("cross_", "")
        from .analyze import FAMILY_SELF
        if t in FAMILY_SELF.get(j.get("family", ""), set()):
            continue
        if (j["judgment"] or {}).get("answered_yes") is True:
            yes[j["model_id"]].add(t)

    top = sorted(yes.items(), key=lambda x: -len(x[1]))[:16]
    names = [reg.get(m, {}).get("name", m) for m, _ in top]
    M = np.zeros((len(top), len(targets)))
    for i, (m, ts) in enumerate(top):
        for jx, t in enumerate(targets):
            M[i, jx] = 1 if t in ts else 0

    fig, ax = plt.subplots(figsize=(7.6, 5.2))
    ax.imshow(M, cmap=matplotlib.colors.ListedColormap(["#fcfcfb", CAT[0]]),
              aspect="auto", vmin=0, vmax=1)
    for i in range(len(top)):
        for jx in range(len(targets)):
            if M[i, jx]:
                ax.text(jx, i, "yes", ha="center", va="center", fontsize=7, color="#ffffff")
    ax.set_xticks(range(len(targets)), ["ChatGPT", "Claude", "Gemini", "DeepSeek", "Qwen",
                                        "Llama", "Grok", "Kimi", "Mistral", "Doubao"],
                  fontsize=8, rotation=30, ha="right")
    ax.set_yticks(range(len(top)), names, fontsize=8)
    style(ax, bottom=False)
    n_any = len(yes)
    ax.set_title(f'"Are you {{X}}?" — models that answered yes (top 16 of {n_any} accepting any)',
                 loc="left", fontsize=11, pad=12)
    save(fig, "fig4_cross_acceptance.png")


def fig5(rows, reg):
    groups = {"correct": Counter(), "foreign": Counter()}
    for j in rows:
        if j["prompt_category"] in ("probe_cross", "system_probe"):
            continue
        jm = j["judgment"]
        if not j.get("had_reasoning"):
            continue
        stance = jm.get("reasoning_identity_stance")
        if stance not in ("asserts", "role_play", "uncertain"):
            continue
        grp = "foreign" if foreign_claims(j) else "correct"
        groups[grp][stance] += 1

    cats = ["asserts", "role_play", "uncertain"]
    labels = {"asserts": "asserts identity", "role_play": "role-plays identity",
              "uncertain": "uncertain about identity"}
    fig, ax = plt.subplots(figsize=(7.4, 2.9))
    names = [f"Foreign self-ID\n(n={sum(groups['foreign'].values()):,})",
             f"Correct self-ID\n(n={sum(groups['correct'].values()):,})"]
    left = np.zeros(2)
    for k, c in enumerate(cats):
        vals = np.array([
            100 * groups["foreign"].get(c, 0) / max(sum(groups["foreign"].values()), 1),
            100 * groups["correct"].get(c, 0) / max(sum(groups["correct"].values()), 1),
        ])
        b = ax.barh(names, vals, left=left, height=0.56, color=CAT[k], label=labels[c],
                    edgecolor=SURFACE, linewidth=2, zorder=3)
        for i, r in enumerate(b):
            if vals[i] > 8:
                ax.text(left[i] + vals[i] / 2, i, f"{vals[i]:.0f}%", ha="center",
                        va="center", fontsize=8.5,
                        color="#ffffff" if k != 2 else INK)
        left += vals
    ax.set_xlim(0, 100)
    ax.set_xticks([])
    ax.legend(loc="upper center", bbox_to_anchor=(0.5, -0.14), ncol=3, frameon=False, fontsize=8.5)
    style(ax, bottom=False)
    ax.set_title("How reasoning traces treat the model's own identity — records with identity content in CoT",
                 loc="left", fontsize=11, pad=12)
    save(fig, "fig5_reasoning_stance.png")


def fig7(rows, reg):
    """Generational scrub-out: identity-drift rate across model generations."""
    series = {
        "Kimi K2 line": ["moonshotai/kimi-k2", "moonshotai/kimi-k2-0905",
                         "moonshotai/kimi-k2-thinking", "moonshotai/kimi-k2.5",
                         "moonshotai/kimi-k2.6", "moonshotai/kimi-k2.7-code"],
        "Qwen large line": ["qwen/qwen-2.5-72b-instruct", "qwen/qwen3-235b-a22b",
                            "qwen/qwen3-max-thinking", "qwen/qwen3.5-397b-a17b",
                            "qwen/qwen3.7-max"],
        "DeepSeek chat line": ["deepseek/deepseek-chat", "deepseek/deepseek-chat-v3-0324",
                               "deepseek/deepseek-chat-v3.1", "deepseek/deepseek-v3.2",
                               "deepseek/deepseek-v4-flash"],
    }
    per = defaultdict(lambda: [0, 0])
    for j in rows:
        if j["prompt_category"] in ("probe_cross", "system_probe"):
            continue
        per[j["model_id"]][1] += 1
        if foreign_claims(j):
            per[j["model_id"]][0] += 1

    fig, ax = plt.subplots(figsize=(8.4, 3.8))
    for k, (label, mids) in enumerate(series.items()):
        xs, ys, ticklabels = [], [], []
        for mid in mids:
            d, n = per.get(mid, (0, 0))
            if n < 50:
                continue
            xs.append(len(xs))
            ys.append(100 * d / n)
            ticklabels.append(reg.get(mid, {}).get("name", mid).replace("Kimi ", "").replace("Qwen", "Q").replace("DeepSeek ", ""))
        ax.plot(xs, ys, "-o", color=CAT[k], label=label, lw=2, ms=6, zorder=3)
        for x, y, tl in zip(xs, ys, ticklabels):
            ax.annotate(tl, (x, y), textcoords="offset points", xytext=(0, 8),
                        fontsize=6.5, color=INK2, ha="center")
    ax.set_ylabel("% identity prompts discrepant")
    ax.set_xticks([])
    ax.set_xlabel("release order →")
    ax.set_ylim(bottom=0)
    ax.yaxis.grid(True, color=GRID, lw=0.8)
    ax.set_axisbelow(True)
    ax.legend(frameon=False, fontsize=8.5, loc="upper right")
    style(ax)
    ax.set_title("The scrub-out: foreign-identity rate across successive releases",
                 loc="left", fontsize=11, pad=12)
    save(fig, "fig7_generational_scrubout.png")


if __name__ == "__main__":
    reg = {m["id"]: m for m in json.loads((ROOT / "config" / "models.json").read_text())["models"]}
    rows = load()
    print(f"{len(rows)} judged records")
    fig3(rows, reg)
    fig4(rows, reg)
    fig5(rows, reg)
    fig7(rows, reg)
